"""Shared contracts for Kian Trading Intelligence.

This package contains Pydantic models and enumerations shared across
backend services, agents, and API boundaries.

Architecture Decisions: AD-003 (Hybrid Low-Token Intelligence),
AD-004 (Four Agents + Risk Kernel), AD-014 (Deterministic Execution),
AD-021 (Shared Market Data).
"""

from contracts.agents import (
    AGENT_PERMISSIONS,
    AGENT_PROHIBITIONS,
    ALL_AGENT_TYPES,
    AgentContext,
    AgentId,
    AgentPermission,
    AgentProhibition,
    AgentResult,
    AgentType,
    DecisionTrace,
    DecisionTraceEntry,
    DecisionTraceId,
)
from contracts.enums import OperatingMode, OrderState, SessionState
from contracts.exchange import (
    ClientOrderId,
    ExchangeOrder,
    ExchangeOrderId,
    ExchangeSubmissionResult,
    FillResult,
    FillStatus,
    OrderSide,
    OrderType,
)
from contracts.identity import (
    ROLE_PRIVILEGE_LEVEL,
    AuditEvent,
    AuditEventId,
    AuditEventType,
    AuthSession,
    CredentialType,
    Device,
    DeviceStatus,
    MFAMethod,
    SessionStatus,
    Tenant,
    TenantId,
    TradingProfile,
    User,
    UserId,
    UserRole,
    can_manage_role,
)
from contracts.indicators import (
    CandleSeries,
    IndicatorResult,
    exponential_moving_average,
    relative_strength_index,
    simple_moving_average,
    volatility,
)
from contracts.ledger import (
    ASSET_PRECISION,
    DEFAULT_PRECISION,
    AccountId,
    AccountSide,
    AccountType,
    FillLedgerMapping,
    FinancialAccount,
    JournalEntry,
    JournalEntryId,
    JournalEntryType,
    JournalLine,
    ProfitLoss,
    ProfitReservationEntry,
    ProfitReservationId,
    ProfitThreshold,
    ProfitThresholdId,
    ProfitThresholdType,
    ReconciliationId,
    ReconciliationRecord,
    ReconciliationStatus,
    WithdrawalRequestId,
    WithdrawalStatus,
    get_precision,
    quantize,
)
from contracts.ledger import (
    ReservationStatus as LedgerReservationStatus,
)
from contracts.llm_gateway import (
    FORBIDDEN_LLM_USES,
    LLMGateway,
    LLMGatewayError,
    LLMRequest,
    LLMRequestId,
    LLMRequestStatus,
    LLMRequestType,
    LLMResponse,
    TokenBudget,
    TokenBudgetConfig,
    TokenBudgetExceededError,
)
from contracts.market_data import (
    Candle,
    DataStatus,
    EventId,
    FreshnessConfig,
    MarketDataEvent,
    MarketDataEventType,
    OrderBookLevel,
    OrderBookSnapshot,
    ProviderType,
    Symbol,
    Ticker,
    Timeframe,
    Trade,
)
from contracts.mining import (
    BlockReward,
    DepreciationConfig,
    ElectricityConfig,
    EquipmentSpec,
    FailureEvent,
    FailureEventId,
    FailureType,
    HashRate,
    HashRateUnit,
    MiningEquipmentId,
    MiningFinancialEntry,
    MiningHardwareStatus,
    MiningOperationStatus,
    MiningSafetyLimits,
    MiningSafetyState,
    MiningSessionConfig,
    MiningSessionId,
    MiningSimulationResult,
    NetworkDifficulty,
    PoolAdapterId,
    PoolAdapterProtocol,
    PoolConfig,
    PoolPayoutScheme,
    SimulatedPoolAdapter,
    TelemetryHistory,
    TelemetryId,
    TelemetryReading,
    TemperatureAction,
    TemperaturePolicy,
)
from contracts.mode import OperatingModeConfig
from contracts.order import OrderIntent, OrderIntentId
from contracts.risk import (
    LEGAL_SESSION_TRANSITIONS,
    AuthorizationStatus,
    ReservationId,
    ReservationStatus,
    RiskAssessment,
    RiskAuthorization,
    RiskAuthorizationId,
    RiskPolicy,
    RiskPolicyId,
    RiskPolicyStatus,
    RiskReservation,
)
from contracts.strategy import (
    LEGAL_STRATEGY_TRANSITIONS,
    StrategyId,
    StrategyParameters,
    StrategyStatus,
    StrategyVersion,
    StrategyVersionId,
)
from contracts.trading import (
    LEGAL_SESSION_TRANSITIONS as TRADING_SESSION_TRANSITIONS,
)
from contracts.trading import (
    SessionId,
    TradingSession,
)
from contracts.validation import (
    BacktestResult,
    PaperTradeResult,
    ValidationRunId,
    ValidationStage,
    ValidationStatus,
    WalkForwardResult,
    WalkForwardWindow,
    run_backtest,
    run_out_of_sample,
    run_paper_trading,
    run_walk_forward,
)

__all__ = [
    "OperatingMode",
    "OrderState",
    "SessionState",
    "OperatingModeConfig",
    "OrderIntent",
    "OrderIntentId",
    "AuditEvent",
    "AuditEventId",
    "AuditEventType",
    "AuthSession",
    "CredentialType",
    "Device",
    "DeviceStatus",
    "MFAMethod",
    "ROLE_PRIVILEGE_LEVEL",
    "SessionStatus",
    "Tenant",
    "TenantId",
    "TradingProfile",
    "User",
    "UserId",
    "UserRole",
    "can_manage_role",
    # Phase 03 — Market Data
    "Candle",
    "CandleSeries",
    "DataStatus",
    "EventId",
    "FreshnessConfig",
    "IndicatorResult",
    "MarketDataEvent",
    "MarketDataEventType",
    "OrderBookLevel",
    "OrderBookSnapshot",
    "ProviderType",
    "Symbol",
    "Timeframe",
    "Ticker",
    "Trade",
    "exponential_moving_average",
    "relative_strength_index",
    "simple_moving_average",
    "volatility",
    # Phase 04 — Risk Kernel and Trading Execution
    "AuthorizationStatus",
    "ClientOrderId",
    "ExchangeOrder",
    "ExchangeOrderId",
    "ExchangeSubmissionResult",
    "FillResult",
    "FillStatus",
    "LEGAL_SESSION_TRANSITIONS",
    "OrderSide",
    "OrderType",
    "ReservationId",
    "ReservationStatus",
    "RiskAssessment",
    "RiskAuthorization",
    "RiskAuthorizationId",
    "RiskPolicy",
    "RiskPolicyId",
    "RiskPolicyStatus",
    "RiskReservation",
    "SessionId",
    "TradingSession",
    "TRADING_SESSION_TRANSITIONS",
    # Phase 05 — Financial Ledger and Profit Policies
    "ASSET_PRECISION",
    "DEFAULT_PRECISION",
    "AccountId",
    "AccountSide",
    "AccountType",
    "FillLedgerMapping",
    "FinancialAccount",
    "JournalEntry",
    "JournalEntryId",
    "JournalEntryType",
    "JournalLine",
    "LedgerReservationStatus",
    "ProfitLoss",
    "ProfitReservationEntry",
    "ProfitReservationId",
    "ProfitThreshold",
    "ProfitThresholdId",
    "ProfitThresholdType",
    "ReconciliationId",
    "ReconciliationRecord",
    "ReconciliationStatus",
    "WithdrawalRequestId",
    "WithdrawalStatus",
    "get_precision",
    "quantize",
    # Phase 06 — Four-Agent Intelligence
    "AGENT_PERMISSIONS",
    "AGENT_PROHIBITIONS",
    "ALL_AGENT_TYPES",
    "AgentContext",
    "AgentId",
    "AgentProhibition",
    "AgentPermission",
    "AgentResult",
    "AgentType",
    "BacktestResult",
    "DecisionTrace",
    "DecisionTraceEntry",
    "DecisionTraceId",
    "FORBIDDEN_LLM_USES",
    "LLMGateway",
    "LLMGatewayError",
    "LLMRequest",
    "LLMRequestId",
    "LLMRequestStatus",
    "LLMRequestType",
    "LLMResponse",
    "LEGAL_STRATEGY_TRANSITIONS",
    "PaperTradeResult",
    "StrategyId",
    "StrategyParameters",
    "StrategyStatus",
    "StrategyVersion",
    "StrategyVersionId",
    "TokenBudget",
    "TokenBudgetConfig",
    "TokenBudgetExceededError",
    "ValidationRunId",
    "ValidationStage",
    "ValidationStatus",
    "WalkForwardResult",
    "WalkForwardWindow",
    "run_backtest",
    "run_out_of_sample",
    "run_paper_trading",
    "run_walk_forward",
    # Phase 07 — Mining Simulation and Safety
    "BlockReward",
    "DepreciationConfig",
    "ElectricityConfig",
    "EquipmentSpec",
    "FailureEvent",
    "FailureEventId",
    "FailureType",
    "HashRate",
    "HashRateUnit",
    "MiningEquipmentId",
    "MiningFinancialEntry",
    "MiningHardwareStatus",
    "MiningOperationStatus",
    "MiningSafetyLimits",
    "MiningSafetyState",
    "MiningSessionConfig",
    "MiningSessionId",
    "MiningSimulationResult",
    "NetworkDifficulty",
    "PoolAdapterId",
    "PoolAdapterProtocol",
    "PoolConfig",
    "PoolPayoutScheme",
    "SimulatedPoolAdapter",
    "TelemetryHistory",
    "TelemetryId",
    "TelemetryReading",
    "TemperatureAction",
    "TemperaturePolicy",
]

__version__ = "0.7.0"
